<a href="https://colab.research.google.com/github/martinkim1/a-school-lecture/blob/main/%EB%94%A5%EB%9F%AC%EB%8B%9D%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)
c = tf.placeholder(tf.float32)
d = tf.placeholder(tf.float32)

addOperation = tf.add(a,b)
minusOperation = tf.subtract(a,b)
mulOperation = tf.multiply(a,b)
divOperation = tf.div(c,d)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
    sess.run(init)
    print("Plus => ", sess.run(addOperation, {a: [[1,2,3], [1,2,3]], b: [[5,2,3], [1,2,3]]}))
    print("Minus => ", sess.run(minusOperation, {a: [[1,2,3], [1,2,3]], b: [[5,2,3], [1,2,3]]}))
    print("Multiply => ", sess.run(mulOperation, {a: [[1,2,3], [1,2,3]], b: [[5,2,3], [1,2,3]]}))
    print("Div => ", sess.run(divOperation, {c: [[1,2,3], [1,2,3]], d: [[5,2,3], [1,2,3]]}))


Instructions for updating:
Deprecated in favor of operator or tf.math.divide.


Plus =>  [[6 4 6]
 [2 4 6]]
Minus =>  [[-4  0  0]
 [ 0  0  0]]
Multiply =>  [[5 4 9]
 [1 4 9]]
Div =>  [[0.2 1.  1. ]
 [1.  1.  1. ]]


## 3차원 행렬곱

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)

addOperation = tf.matmul(a,b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
    sess.run(init)
    print("Plus => ", sess.run(addOperation, {a: [[1,2,3], [1,2,3], [1,2,3]], b: [[5,2,3], [1,2,3]]}))
    print("Minus => ", sess.run(minusOperation, {a: [[1,2,3], [1,2,3]], b: [[5,2,3], [1,2,3]]}))
    print("Multiply => ", sess.run(mulOperation, {a: [[1,2,3], [1,2,3]], b: [[5,2,3], [1,2,3]]}))
    print("Div => ", sess.run(divOperation, {c: [[1,2,3], [1,2,3]], d: [[5,2,3], [1,2,3]]}))